name: design_system
description: Design system made for all the vetermedi projects
version: 0.0.1
author:
homepage: 'vetermedi.com'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: AppFont
      fonts:
        - asset: fonts/Regular.otf
          weight: 400
        - asset: fonts/Medium.otf
          weight: 500
        - asset: fonts/SemiBold.otf
          weight: 600
        - asset: fonts/Bold.otf
          weight: 700
